require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
      - 'vendor/**/*'
      - 'bin/**/*'
  RSpec:
    Patterns:
      - '.+'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Enabled: false # This project enables to define multiple expectations
